package ats.classifiers;

import java.util.ArrayList;

import weka.core.Instances;

// Find mode of classification results for each instance generated by C4.5Tree, NBTree and LRTRee classifiers
public class MultipleClassifiers {

	private C4_5DecisionTree c4_5Tree = new C4_5DecisionTree();
	private NaiveBayesTree nbTree = new NaiveBayesTree();
	private LRTree lrTree = new LRTree();

	private ArrayList<ArrayList<Double>> classIndices = new ArrayList<ArrayList<Double>>();

	public MultipleClassifiers(C4_5DecisionTree c4_5Tree,
			NaiveBayesTree nbTree, LRTree lrTree) {
		this.c4_5Tree = c4_5Tree;
		this.nbTree = nbTree;
		this.lrTree = lrTree;
	}

	public void applyClassifiers(Instances testData) {

		// Get baseline class indices from test dataset
		ArrayList<Double> baseline = new ArrayList<Double>();
		for (int i = 0; i < testData.numInstances(); i++) {
			baseline.add(testData.get(i).value(testData.numAttributes() - 1));
		}

		classIndices.add(0, baseline);
		classIndices.add(1, c4_5Tree.getClassificationResultSet());
		classIndices.add(2, nbTree.getClassificationResultSet());
		classIndices.add(3, lrTree.getClassificationResultSet());

		ArrayList<Double> multipleClassificationResultSet = new ArrayList<Double>();

		for (int i = 0; i < baseline.size(); i++) {
			if (classIndices.get(1).get(i).equals(classIndices.get(2).get(i))
					|| classIndices.get(1).get(i).equals(
							classIndices.get(3).get(i))) {
				multipleClassificationResultSet.add(i, classIndices.get(1).get(
						i));
			} else if (classIndices.get(2).get(i).equals(
					classIndices.get(3).get(i))) {
				multipleClassificationResultSet.add(i, classIndices.get(2).get(
						i));
			} else {
				multipleClassificationResultSet.add(i, classIndices.get(1).get(
						i));
			}
		}

		classIndices.add(4, multipleClassificationResultSet);

		double score = 0;
		for (int i = 0; i < baseline.size(); i++) {
			if (classIndices.get(0).get(i).equals(classIndices.get(4).get(i))) {
				score++;
			}
		}
		score = score / 78.0;
		System.out.println("\nscore: " + score * 100
				+ " % Correctly Classified Instances");
	}
}
